spring:
  profiles:
    include:
      - oauth2
      - stmp
  application:
    name: todo

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/DB # 파일기반 H2 데이터베이스
    username: todo
    password :

#      name: user
  # 개발시에만 H2 Console 설정
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

server:
  url: ${SERVER_URL}

front:
  url: ${FRONT_URL}


logging:
  level:
    org:
      springframework:
        mail: DEBUG
      eclipse:
        angus:
          mail: DEBUG
