spring:

  application:
    name: todo

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todo
    username: todo
    password :
# h2-console
#  security:
#    user:
#      name: user
#      password: 1234
  # 개발시에만 H2 Console 설정
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true



